Update scripts_with_pip.yml

diff --git a/.github/workflows/scripts_with_pip.yml b/.github/workflows/scripts_with_pip.yml
--- a/.github/workflows/scripts_with_pip.yml
+++ b/.github/workflows/scripts_with_pip.yml
@@ -1,4 +1,4 @@
-name: Run Python Scripts
+name: Run Scripts Without pip
 
 on:
   push:
@@ -17,24 +17,28 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     
-    - name: Set up Python
+    - name: Set up Python 3.12.5
       uses: actions/setup-python@v2
       with:
-        python-version: '3.x'
-    
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        python -m spacy download es_core_news_sm
-        python -m nltk.downloader wordnet
+        python-version: '3.12.5'
     
     - name: Run scripts
       run: |
-        cd scripts
-        python run_plagiarism_1.py
-        python extract_elements.py
-        python analyze_spelling.py
+        scripts=(
+          "analyze_libraries.py"
+          "analyze_structure.py"
+          "analyze_identation.py"
+          
+        )
+        for script in "${scripts[@]}"
+        do
+          if [ -f "scripts/$script" ]; then
+            echo "Running $script"
+            python "scripts/$script" || echo "Script $script failed, but continuing..."
+          else
+            echo "Script $script not found in scripts folder"
+          fi
+        done
       shell: bash
     
     - name: Always succeed
